server {
    listen 80;
    
    # Thư mục chứa code đã build
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Cấu hình quan trọng cho React Router:
    # Nếu không tìm thấy file thực tế, luôn trả về index.html để React xử lý routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}